#!/bin/bash
#
#variables
codes_file="codes" # temporal file for the code posts
exts_list=( "mp4" "mov720.mp4" "mov.mp4" "pic.jpg" "picsmall.jpg" )

echo -e "\e[34mPaste an url playlist:\e[0m"

read URL

URL=$(echo $URL | sed "s@https://@@")

# get title
title=$( curl -Ls $URL | grep -o 'class="text fill">[^<]*' | cut -d '>' -f 2 )

# create the playlist folder
mkdir "$title"

echo -e "\e[34mDownloading Playlist: $title\e[0m"

curl -Ls $URL | grep -oP "/post/.*?\"" | sed "s@/post/@@" | sed 's@"@@' > $codes_file


# read every url lines of codes.txt
while IFS= read -r code; do

    rest="${code%???}"             # get the range first numbers before 3 last numbers

    #database pattern
    url_in="https://rule34storage.b-cdn.net/posts/$rest/$code/$code"

    # download and verify if the file extension is correct
    for extension in "${exts_list[@]}"
    do
        curl --silent -e "https://rule34.world" -L "$url_in.$extension" -o "$title/$code.$extension"
        size=$(ls -l "$title/$code.$extension" | cut -d ' ' -f 5)
        if [ $((size)) -le 900 ]
        then
#            echo -e "\e[35m$code is not $extension\e[0m"
            rm "$title/$code.$extension"
        else
            echo -e "\e[33m$code.$extension downloaded.\e[0m"
            break
        fi
    done


done < $codes_file

rm $codes_file

#finished

echo -e "\e[32mPlaylist $title download complete.\e[0m"
